<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('classes')->insert([
            [
                'ClassId' => 1,
                'LecturerId' => 'DW211',
                'CourseId' => 'COMP6360004',
                'ClassCode' => 'BC20',
                'LecturerRoleId' => 2,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LAB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 2,
                'LecturerId' => 'D6671',
                'CourseId' => 'COMP6360004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 26,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 3,
                'LecturerId' => 'D3708',
                'CourseId' => 'COMP6764004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 4,
                'LecturerId' => 'D5975',
                'CourseId' => 'MATH6119004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 5,
                'LecturerId' => 'D6365',
                'CourseId' => 'MATH6118004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 26,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 6,
                'LecturerId' => 'D6404',
                'CourseId' => 'COMP6840004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 7,
                'LecturerId' => 'D6071',
                'CourseId' => 'CHAR6030004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 8,
                'LecturerId' => 'D5848',
                'CourseId' => 'LANG6117004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 1,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            # Semester 2
            [
                'ClassId' => 9,
                'LecturerId' => 'D6261',
                'CourseId' => 'COMP6362004',
                'ClassCode' => 'BC20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 12,
                'CourseCategory' => 'LAB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 10,
                'LecturerId' => 'D6261',
                'CourseId' => 'COMP6851004',
                'ClassCode' => 'BC20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 6,
                'CourseCategory' => 'LAB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 11,
                'LecturerId' => 'D3708',
                'CourseId' => 'MATH6193004',
                'ClassCode' => 'BC20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 6,
                'CourseCategory' => 'LAB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 12,
                'LecturerId' => 'D5848',
                'CourseId' => 'MATH6120004',
                'ClassCode' => 'BC20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 26,
                'CourseCategory' => 'LAB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 13,
                'LecturerId' => 'D6071',
                'CourseId' => 'CHAR6031004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 14,
                'LecturerId' => 'D6365',
                'CourseId' => 'COMP6362004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 26,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 15,
                'LecturerId' => 'D6365',
                'CourseId' => 'ENTR6519002',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 16,
                'LecturerId' => 'D6261',
                'CourseId' => 'COMP6851004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 17,
                'LecturerId' => 'D3708',
                'CourseId' => 'MATH6193004',
                'ClassCode' => 'LB20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2022,
                'Semester' => 2,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            # Semester 3
            [
                'ClassId' => 18,
                'LecturerId' => 'D6394',
                'CourseId' => 'SCIE6067004',
                'ClassCode' => 'BF20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2023,
                'Semester' => 3,
                'NumberOfSession' => 6,
                'CourseCategory' => 'LAB',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            # Semester 7
            [
                'ClassId' => 19,
                'LecturerId' => 'D6494',
                'CourseId' => 'COMP6426001',
                'ClassCode' => 'LA20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2025,
                'Semester' => 7,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 20,
                'LecturerId' => 'D6494',
                'CourseId' => 'COMP6762001',
                'ClassCode' => 'LA20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2025,
                'Semester' => 7,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ClassId' => 21,
                'LecturerId' => 'D6494',
                'CourseId' => 'COMP6514001',
                'ClassCode' => 'LA20',
                'LecturerRoleId' => 1,
                'ClassYear' => 2025,
                'Semester' => 7,
                'NumberOfSession' => 13,
                'CourseCategory' => 'LEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
